apiVersion: v1
kind: Pod
metadata:
  name: pod-with-metadata-env
spec:
  containers:
  - image: busybox
    name: demo
    command: ["sleep","9999999"]
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP