apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: demo
        image: hellozin/demo